//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownLoadMP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Album { get; set; }
        public string Singer { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string DownLoadUrl { get; set; }
        public string ThunderDownLoadUrl { get; set; }
        public bool IsDownloaded { get; set; }
    }
}
